//! Writes `OUT_DIR/build_info.rs` so build time changes invalidate the crate reliably.
//! On Windows, embeds `assets/rustdl.ico` into the `.exe` (Explorer, shortcuts).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out = Path::new(&out_dir);
    let now = chrono::Utc::now();
    let unix = now.timestamp();

    fs::write(
        out.join("build_info.rs"),
        format!(
            "// @generated by build.rs — do not edit\n\
             pub const BUILD_UNIX: i64 = {unix};\n\
             pub const BUILD_DATE_UTC: &str = \"{}\";\n",
            now.format("%Y-%m-%d %H:%M UTC")
        ),
    )
    .expect("write build_info.rs");

    // Updating the stamp makes the next `cargo build` re-run this script even when no
    // source files changed (so About / --version always reflect the latest link).
    let stamp = out.join(".build-stamp");
    fs::write(&stamp, unix.to_string()).expect("write build stamp");
    println!("cargo:rerun-if-changed={}", stamp.display());

    #[cfg(windows)]
    {
        println!("cargo:rerun-if-changed=assets/rustdl.ico");
        let mut res = winres::WindowsResource::new();
        res.set_icon("assets/rustdl.ico");
        res.compile()
            .expect("failed to embed Windows executable icon");
    }
}
